### ISSUE TITLE
Sporadic 500, “FUNCTION_INVOCATION_FAILED”

### ISSUE THREAD

**Issue by tophtucker** [tophtucker/appletreeinn#30]
![image](https://github.com/tophtucker/appletreeinn/assets/841829/55794215-95b6-449a-8442-e0a457e48b8f)

**Comment by tophtucker** [comment]
This Serverless Function has crashed.

Your connection is working correctly.

Vercel is working correctly.

500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
ID: iad1::2tjps-1719867215244-6682603d4a3b
If you are a visitor, contact the website owner or try again later.

**Comment by tophtucker** [comment]
```
Unhandled Rejection: TypeError: fetch failed
at node:internal/deps/undici/undici:12502:13
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async loadEvents (file:///var/task/.svelte-kit/output/server/chunks/index3.js:3:24)
at async file:///var/task/.svelte-kit/output/server/entries/pages/_page.svelte.js:52:12 {
[cause]: ConnectTimeoutError: Connect Timeout Error (attempted addresses: 172.253.115.138:443)
at onConnectTimeout (node:internal/deps/undici/undici:6635:28)
at node:internal/deps/undici/undici:6587:50
at Immediate._onImmediate (node:internal/deps/undici/undici:6619:13)
at process.processImmediate (node:internal/timers:478:21)
at process.callbackTrampoline (node:internal/async_hooks:130:17) {
code: 'UND_ERR_CONNECT_TIMEOUT'
}
}
Node.js process exited with exit status: 128. The logs above can help with debugging the issue.
```
